### PR TITLE
Brian's homework

### PR DESCRIPTION
**Pull request by brianward**
Hi Renee - I'm out of town for work this week so I'm just now submitting my homework as I remember you asking that we didn't submit it before class today. Let me know if this is an issue or is late. Thanks.

### CODE REVIEW

**Comment by reneedv** [comment]
Hi Brian, 
  You're not late! No worries!
   Did you see the questions.txt file in the week1 homework directory? It has the questions on the reading assignment. Please update your pull request with your answers.
Thanks!
**Renée

**Comment by brianward** [comment]
Thanks Renee - done.

**Comment by brianward** [comment]
Homework now submitted for Week2

**Comment by nellshamrell** [comment]
Homework looks good!

**Pull request closed without merging**
